Repository amplitude/Amplitude-TypeScript, pull requests merged in 2023-06, with the labels that each got.

#409 build: remove unnecessary beta script guard
  scripts/version/create-snippet.js
Labels: v1.x

#400 fix: don't automatically start new session on setUserId
  packages/analytics-browser-test/test/index.test.ts
  packages/analytics-browser/src/browser-client.ts
  packages/analytics-browser/test/browser-client.test.ts
Labels: v1.x

#415 feat: log response body from API to logger
  packages/analytics-core/src/plugins/destination.ts
  packages/analytics-core/test/plugins/destination.test.ts
  packages/analytics-node/src/transports/http.ts
  packages/analytics-types/src/response.ts
Labels: v1.x

#425 feat: added extendSession() method to Browser Client
  packages/analytics-browser/src/browser-client-factory.ts
  packages/analytics-browser/src/browser-client.ts
  packages/analytics-browser/src/index.ts
  packages/analytics-browser/test/browser-client.test.ts
  packages/analytics-browser/test/helpers/mock.ts
  packages/analytics-browser/test/index.test.ts
  packages/analytics-react-native/src/react-native-client.ts
  packages/analytics-types/src/client/web-client.ts
Labels: v1.x

#424 fix: do not fetch advertising Id if adid tracking is disabled
  packages/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AmplitudeReactNativeModule.kt
  packages/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AndroidContextProvider.kt
  packages/analytics-react-native/ios/AmplitudeReactNative.m
  packages/analytics-react-native/ios/AmplitudeReactNative.swift
  packages/analytics-react-native/src/plugins/context.ts
Labels: v1.x

#431 fix: session end events being assigned to a different session id (#426)
  packages/analytics-browser-test/test/index.test.ts
  packages/analytics-browser/src/browser-client.ts
  packages/analytics-browser/src/cookie-migration/index.ts
  packages/analytics-browser/src/plugins/context.ts
  packages/analytics-browser/src/plugins/session-handler.ts
  packages/analytics-browser/test/browser-client.test.ts
  packages/analytics-browser/test/config.test.ts
  packages/analytics-browser/test/cookie-migration/index.test.ts
  packages/analytics-browser/test/plugins/context.test.ts
  packages/analytics-browser/test/plugins/session-handler.test.ts
Labels: v1.x

#417 build: update default dist-tag and pre-dist-tag
  .github/workflows/publish-v1.yml
  .github/workflows/publish-v2.yml
  packages/analytics-browser/package.json
  packages/analytics-client-common/package.json
  packages/analytics-core/package.json
  packages/analytics-node/package.json
  packages/analytics-react-native/package.json
  packages/analytics-types/package.json
  packages/plugin-page-view-tracking-browser/package.json
  packages/plugin-web-attribution-browser/package.json
Labels: do not merge

#418 build: update dist-tag
  packages/analytics-browser/package.json
  packages/analytics-client-common/package.json
  packages/analytics-core/package.json
  packages/analytics-node/package.json
  packages/analytics-react-native/package.json
  packages/analytics-types/package.json
  packages/marketing-analytics-browser/package.json
  packages/plugin-page-view-tracking-browser/package.json
  packages/plugin-web-attribution-browser/package.json
Labels: do not merge, v1.x

#430 fix: compact logged response body's for AMP-77261
  packages/analytics-core/src/plugins/destination.ts
  packages/analytics-core/test/plugins/destination.test.ts
Labels: v1.x

#463 fix: allow plugins to teardown to remove listeners
  packages/analytics-browser/src/plugins/file-download-tracking.ts
  packages/analytics-browser/src/plugins/form-interaction-tracking.ts
  packages/analytics-browser/test/plugins/file-download-tracking.test.ts
  packages/analytics-browser/test/plugins/form-interaction-tracking.test.ts
  packages/analytics-core/src/timeline.ts
  packages/analytics-core/test/timeline.test.ts
  packages/analytics-types/src/plugin.ts
  packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts
  packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts
Labels: v1.x
